#!/usr/bin/env python3
"""
issue_token.py — idempotent bootstrap of the per-user NTFY publish + subscribe
tokens for the Atlas stack.

Per PHASE2-SPEC.md §2.4, the model is:
  - Two tokens, both scoped to a single topic `atlas-<userid>`.
  - Publish token   (e.g. `tk_AgQdq7mVBoFD37zQVN29RhuMzNIz2`)
                    — write-only on the topic, held by atlas-notifier
                    as NTFY_PUBLISH_TOKEN.
  - Subscribe token (e.g. `tk_B3fN8cQ2xL9pKvR7wY4hJ6mT1aZ0dS5u`)
                    — read-only on the topic, held by the iOS NTFY app.
  - The split is so that a leaked publish token can't subscribe, and vice
    versa. The subscribe token in particular should never leave the iOS
    device.
  - The spec's §2.4 uses the names `tk_atlas_<userid>_publish` and
    `tk_atlas_<userid>_subscribe` as a mnemonic. The actual token values
    are random base64 strings generated by NTFY's `token add` command —
    we track them by their LABEL (`atlas-publish` and `atlas-subscribe`),
    not by their value, so rotation is independent of identity.

The way NTFY actually models this: tokens are per-user, and ACLs determine
what a user may do. So we provision TWO users — `<userid>` (the iOS
subscriber) and `<userid>-publisher` (the notifier) — and give each a
narrowly-scoped ACL on the shared topic. The script then issues one token
per user, both labelled for easy rotation tracking.

Idempotency contract:
  - Users are created only if missing (NTFY's `user add` errors otherwise).
  - ACLs are upserted (NTFY's `access` with --reset replaces any prior rule
    for the same <user, topic>).
  - Tokens are NEVER reissued. NTFY's `token add` always generates a new
    random token. We look up the existing token for the user (filtered by
    label) and print it; if none exists, we generate one. Rotating a token
    means deleting the old one with `ntfy token remove` and re-running this
    script — that is the documented rotation flow, NOT a re-run.

Install flow (one-time, run by hand on openclaw):

  1. Bring up the atlas-ntfy container: `docker compose up -d ntfy`
  2. Wait for healthcheck (`docker compose ps ntfy` shows "healthy").
  3. Run this script:
         uv run --with ./pyproject.toml docker/ntfy/issue_token.py --user-id anurag
     (The script prompts for a password for the iOS subscriber. The
     password is set once and is what the iOS NTFY app authenticates with
     under the hood. The publisher user gets a random password — never
     typed by a human — and is only used via its token.)
  4. Copy the two printed tokens into:
         docker/notifier/.env  → NTFY_PUBLISH_TOKEN=tk_atlas_<userid>_publish
         iOS NTFY app          → paste `tk_atlas_<userid>_subscribe` into
                                 the subscription's auth field
  5. The tokens are NEVER committed to git. `.env` is gitignored; the
     tokens printed here are the only copy.

Re-running with the same --user-id will:
  - Skip user creation (they exist)
  - Re-upsert the ACL rules (idempotent)
  - Print the EXISTING tokens (idempotent — no token rotation)

Usage:
  uv run --with ./pyproject.toml docker/ntfy/issue_token.py --user-id <userid>
  uv run --with ./pyproject.toml docker/ntfy/issue_token.py --user-id anurag --ntfy-container atlas-ntfy
"""
from __future__ import annotations

import argparse
import getpass
import secrets
import subprocess
import sys

# ---------------------------------------------------------------------------
# Defaults — these match PHASE2-SPEC.md §2.1 / §2.4 / §3. Override via flags
DEFAULT_NTFY_CONTAINER = "atlas-ntfy"
DEFAULT_NTFY_AUTH_DB = "/var/lib/ntfy/auth.db"
PUBLISHER_USER_SUFFIX = "-publisher"
PUBLISH_LABEL = "atlas-publish"
SUBSCRIBE_LABEL = "atlas-subscribe"
TOPIC_PREFIX = "atlas-"


# ---------------------------------------------------------------------------
# Helpers — thin wrappers over `docker exec atlas-ntfy ntfy ...` and the
# `sqlite3` CLI that ships inside the ntfy image.
# ---------------------------------------------------------------------------

def docker_exec(container: str, *args: str, input_text: str | None = None) -> str:
    """Run a command inside the ntfy container, return stdout (stripped)."""
    cmd = ["docker", "exec", "-i", container, *args]
    result = subprocess.run(
        cmd,
        input=input_text,
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"command failed (rc={result.returncode}): {' '.join(cmd)}\n"
            f"  stderr: {result.stderr.strip()}"
        )
    return result.stdout.strip()


def ntfy(container: str, *args: str, input_text: str | None = None) -> str:
    """Run `ntfy <subcommand>` inside the container."""
    return docker_exec(container, "ntfy", *args, input_text=input_text)


def sqlite_query(container: str, db_path: str, sql: str) -> str:
    """Run a SQL query against the ntfy auth DB inside the container.

    We pipe the query via stdin (`sqlite3 :memory: < query.sql` is awkward;
    the simplest portable form is to pass the query as an argument).
    """
    return docker_exec(container, "sqlite3", "-separator", "\t", db_path, sql)


# ---------------------------------------------------------------------------
# SQLite schema for NTFY's auth.db (verified against the upstream source:
# https://github.com/binwiederhier/ntfy/blob/main/user/db_migration.go).
# We rely on the table + column names being stable. If NTFY ever changes them,
# this script breaks loudly.
# ---------------------------------------------------------------------------
TOKEN_QUERY = """
SELECT t.value, t.label
FROM tokens t
JOIN users u ON u.id = t.user_id
WHERE u.name = '{user}' AND t.label = '{label}'
ORDER BY t.created ASC
LIMIT 1
"""

# Sanity: what tables/columns does the running ntfy use? Cached per-process
# so we only probe once.
_SCHEMA_PROBED = False


def probe_schema(container: str, auth_db: str) -> None:
    """Verify the expected tables/columns exist. Fail loudly if NTFY
    upstream has renamed something."""
    global _SCHEMA_PROBED
    if _SCHEMA_PROBED:
        return
    out = sqlite_query(
        container,
        auth_db,
        "SELECT name FROM sqlite_master WHERE type='table' AND name IN ('users','tokens','access')",
    )
    found = set(out.splitlines())
    missing = {"users", "tokens", "access"} - found
    if missing:
        raise RuntimeError(
            f"ntfy auth.db at {auth_db} is missing tables: {sorted(missing)}. "
            f"Found: {sorted(found)}. The NTFY schema may have changed "
            f"upstream; pin to a known version or update this script."
        )
    _SCHEMA_PROBED = True


# ---------------------------------------------------------------------------
# Per-user provisioning steps. Each is a thin, named function so the top-
# level flow reads as a recipe.
# ---------------------------------------------------------------------------

def ensure_user(container: str, username: str, password: str | None) -> None:
    """Create user if missing. NTFY's `user add` errors if the user exists;
    we treat any error as 'probably already exists' and verify with `user list`."""
    try:
        # `ntfy user add` prompts for password if not given; pass via stdin.
        ntfy(container, "user", "add", "--role=user", username,
             input_text=(password + "\n" if password is not None else None))
    except RuntimeError as err:
        # Most likely: user already exists. Confirm with a list.
        listing = ntfy(container, "user", "list")
        if username in listing.splitlines():
            return  # already exists; idempotent OK
        raise RuntimeError(
            f"failed to create user {username!r} and it does not appear in "
            f"`ntfy user list`. Original error:\n{err}"
        ) from err


def ensure_acl(container: str, username: str, topic: str, permission: str) -> None:
    """Upsert a single ACL entry. `--reset` makes this idempotent (any
    prior rule for the same <user, topic> is replaced)."""
    ntfy(container, "access", username, topic, permission, "--reset")


def ensure_token(container: str, username: str, label: str) -> str:
    """Return the existing token for (user, label), or generate a new one.

    Idempotency: we look up the token by label in the auth DB. If absent,
    we call `ntfy token add` which always generates a new random token.
    Re-running this script will return the SAME token because the lookup
    is by label, and the label is the human-visible identity.
    """
    sql = TOKEN_QUERY.format(user=username, label=label)
    out = sqlite_query(container, DEFAULT_NTFY_AUTH_DB, sql)
    if out:
        value, _ = out.split("\t", 1)
        return value
    # Not present — generate. The token is printed to stdout by NTFY.
    new_token = ntfy(container, "token", "add", "--label=" + label, username)
    # NTFY may print "Token added: tk_..." or just "tk_...". Normalize.
    if new_token.startswith("Token added:"):
        new_token = new_token.split(":", 1)[1].strip()
    return new_token


def topic_for(userid: str) -> str:
    """`atlas-<userid>`. Lowercased to satisfy NTFY's URL-safe constraint."""
    return TOPIC_PREFIX + userid.lower()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Idempotently issue publish + subscribe tokens for an Atlas NTFY user.",
    )
    parser.add_argument(
        "--user-id",
        required=True,
        help="The Open WebUI / iOS user id (e.g. 'anurag'). The topic will be 'atlas-<user-id>'.",
    )
    parser.add_argument(
        "--ntfy-container",
        default=DEFAULT_NTFY_CONTAINER,
        help=f"NTFY container name (default: {DEFAULT_NTFY_CONTAINER}).",
    )
    parser.add_argument(
        "--auth-db",
        default=DEFAULT_NTFY_AUTH_DB,
        help=f"Path to auth.db inside the container (default: {DEFAULT_NTFY_AUTH_DB}).",
    )
    args = parser.parse_args()

    userid = args.user_id.strip().lower()
    if not userid or not userid.replace("-", "").replace("_", "").isalnum():
        print(f"error: --user-id must be alphanumeric (with optional -/_): {userid!r}",
              file=sys.stderr)
        return 2

    topic = topic_for(userid)
    publisher = userid + PUBLISHER_USER_SUFFIX

    # Schema check (loud failure if upstream changed).
    probe_schema(args.ntfy_container, args.auth_db)

    # 1. Subscriber user (iOS). Prompts for a password — this is the
    # password the iOS NTFY app will store. It is only typed once, on
    # first install. If the user already exists, the prompt is skipped
    # (the password is already set).
    subscriber_password = getpass.getpass(
        f"Enter iOS subscriber password for user {userid!r} "
        f"(leave empty to keep existing; Ctrl-C to abort): "
    )
    ensure_user(args.ntfy_container, userid, subscriber_password or None)

    # 2. Publisher user (atlas-notifier). Random password — never typed by
    # a human, the notifier authenticates by token only. We pass a fixed-
    # length random string and immediately forget it.
    import secrets
    publisher_password = secrets.token_urlsafe(24)
    ensure_user(args.ntfy_container, publisher, publisher_password)

    # 3. ACL rules. Both users share the same topic, with split permissions.
    # `auth-default-access: deny-all` means the topic is closed to everyone
    # by default; these two rules are what open it up. Order: subscriber
    # gets read-only (so iOS can listen), publisher gets write-only (so the
    # notifier can publish). The publisher can never read the topic, even
    # if its token leaks; the subscriber can never write.
    ensure_acl(args.ntfy_container, userid, topic, "read-only")
    ensure_acl(args.ntfy_container, publisher, topic, "write-only")

    # 4. Tokens. We never reissue (that would invalidate the iOS app and
    # the notifier's NTFY_PUBLISH_TOKEN env var). The lookup-by-label is
    # what makes the whole script idempotent.
    subscribe_tok = ensure_token(args.ntfy_container, userid, SUBSCRIBE_LABEL)
    publish_tok = ensure_token(args.ntfy_container, publisher, PUBLISH_LABEL)

    # 5. Print the tokens in a copy-pasteable form. NO real tokens are
    # committed to this file — only this print, at install time.
    print()
    print(f"Topic:   {topic}")
    print(f"Subscribe token (paste into the iOS NTFY app subscription auth):")
    print(f"  {subscribe_tok}")
    print(f"Publish token (set as NTFY_PUBLISH_TOKEN in docker/notifier/.env):")
    print(f"  {publish_tok}")
    print()
    print("Re-running with the same --user-id will print the same tokens (idempotent).")
    print("To rotate, run `ntfy token remove` on the old label inside the container first.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
